### ISSUE TITLE
dup?

### ISSUE THREAD

**Issue by sharl** [katonium/articles#1]
https://github.com/katonium/articles/blob/a3263e19031f315cba75e3f65f647c7c31c3a673/articles/slack-go-tsukaou-fileuploadv2.md?plain=1#L2

duplicate ではなく deprecate ではないでしょうか

**Comment by katonium** [comment]
@sharl 

連絡遅くなってしまい申し訳ありません。

ご指摘ありがとうございます！ご指摘の通り、"deprecate"が適切でした。
色々調べたところ↓のとおり名詞形としては"duplication"が適切のようでしたので、それにあわせ記事のタイトルも修正しました！

https://qiita.com/seratch/items/971980506da92ea6c8db
